services:
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always

networks:
  db:
    driver: bridge

volumes:
  db: